config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  has_one_attached :profile_image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def get_profile_image(width, height)
        unless profile_image.attached?
          file_path = Rails.root.join('app/assets/images/no_image.jpg')
          profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        profile_image.variant(resize_to_limit: [width,height]).processed
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :books, dependent: :destroy
         
      has_one_attached :profile_image
      
      def get_profile_image(width, height)
        unless profile_image.attached?
          file_path = Rails.root.join('app/assets/images/no_image.jpg')
          profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        profile_image.variant(resize_to_limit: [width,height]).processed
      end
      
      validates :name, length: {minimum: 2, maximum: 20} 
      validates :name, uniqueness: true
      validates :introduction, length: {maximum: 50}

          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    @user
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
   end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id) #本当はbookの詳細画面に飛びたい
    else
    @books = Book.all
    @user = current_user
    render :index
    end
  end


  def index
    @book = Book.new
    @books = Book.all #@user.post_images　ユーザー全ての投稿が見れる場所に飛ばす。15章みて
    @users = User.all
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully"
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    user_id = book.user_id
    unless user_id == current_user.id
      redirect_to books_path
    end
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @books = Book.all
    @user = current_user
    @books = @user.books
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<p id="notice"></p>

        <div class="container px-5 px-sm-0">
          <div class="row">
            <div class="col-md-3">
              <h2>User info</h2>
               <%= image_tag book.user.get_profile_image(100,100) %>
               <table class="table">
                 <tbody>
                   <div>name【<%= book.user.name %>】</div>

                   <div>introduction【<%= book.user.introduction %>】</div>
                 </tbody>
               </table>

        <div class="row">
          <% if @user == current_user %>
            <%= link_to "edit", edit_user_path(@user) %>
          <% end %>
        </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>Editing Book</h2>
  <%= form_with model: @book do |f| %>
  
    <h4>Title</h4>
    <%= f.text_field :title %>
  
    <h4>Body</h4>
    <%= f.text_area :body %>
  
    <%= f.submit 'Update Book' %>
  
  <% end %>
  
  <%= link_to book_path(@book.id) do %>
    Show
  <% end %>
  
  
  <%= link_to books_path do %>
    Back
  <% end %>
    </div>
  </div>  
</div>

app/views/books/index.html.erb
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">

  <body>
    <div>
      <%= flash[:notice] %>

      <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
    </div>


      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <!--多分ヘッダーのなにかをのせるんだとおもう-->
        </nav>
      </header>

      <main>
        <p id="notice"></p>

        <div class="container px-5 px-sm-0">
          <div class="row">
            <!--ここからテンプレート-->
            <div class="col-md-3">
              <h2>User info</h2>
               <%= image_tag @user.get_profile_image(100,100) %>
               <table class="table">
                 <tbody>
                   <div>name【<%= @user.name %>】</div>

                   <div>introduction【<%= @user.introduction %>】</div>
                 </tbody>
               </table>

        <div class="row">
          
            <i class="fas fa-wrench"></i><%= link_to "edit", edit_user_path(@user) %><i class="fas fa-user-cog"></i> <!--後で画像でリンクつなげる-->
          
        </div>


       <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>

           <p>Title</p>
          <%= f.text_field :title %>
          <p>Opinion</p>
          <%= f.text_area :body %>
           <%= f.submit 'Create Book' %>
        <% end %>

            </div>

        <!--ここまでテンプレート-->
         <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          　<table class="table table-hover table-inverse">
          　 <thead>
            　 <tr>
            　    <th></th>
              　   <th>Title</th>
              　   <th>Body</th>
              　   <th colspan="3"></th>
            　 </tr>
          　 </thead>

            <% @books.each do |book| %>
            <thead>
            <tr>
              <th>
                <%= link_to book.user do %>
                  <%= image_tag book.user.get_profile_image(100,100) %></th>
                <% end %>
              <th>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
              </th>
              <th><%= book.body %></th>
              <th colspan="3"><!--３つのリンク--></th>
            </tr>
            </thead>
          <% end %>



          </table>
        </div>
       </div>
      </main>
  </body>
</html>

app/views/books/show.html.erb
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">

  <body>
    <div>
  <%= flash[:notice] %>
    </div>

      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <!--多分ヘッダーのなにかをのせるんだとおもう-->
        </nav>
      </header>

      <main>
        
        <%= render 'books/list', book: @book %>
        

        <div class="row">
          
            <i class="fas fa-wrench"></i><%= link_to "edit", edit_user_path(@book.user) %><i class="fas fa-user-cog"></i> <!--後で画像でリンクつなげる-->
          
        </div>


       <h2 class="mt-3">New book</h2>
        <%= form_with model: @book_new do |f| %>
        <form action="/books" accept-charset="UTF-8" method="post">
           <p>Title</p>
          <%= f.text_field :title %>
          <p>Opinion</p>
          <%= f.text_area :body %>
           <%= f.submit 'Create Book' %>
        <% end %>
        </form>
            </div>

        <!--ここまでテンプレート-->
         <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          　<table class="table table-hover table-inverse">

            <tbody>
              <tr>
                <td>
                  <%= image_tag @book.user.get_profile_image(100,100) %>
                  <p>
                  <%= link_to @book.user do %>
                    <%= @book.user.name %>
                  <% end %>
                  </p>
                   <td>
                     <%= link_to @book_path do %>
                     <%= @book.title %>
                     <% end %>
                   </td>
                  <td><%= @book.body %></td>
                  <th colspan="1">
                    
                <% if @book.user == current_user %>
                    <%= link_to edit_book_path(@book.id) do %>
                      Edit
                    <% end %>

                    <%= link_to book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?" do %>
                      Destroy
                    <% end %>
                <% end %>
                  </th>
                </th>


              </tr>
            </tbody>




          </table>
        </div>
       </div>
      </main>
  </body>
</html>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to <strong><i class="fas fa-book"></i>Bookers</strong> !
      </h1>
    </div>
  </div>
  </div>
</main>

app/views/homes/top.html.erb
<body>
  <header></header>
  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
          <h1>
            Welcome to <strong><i class="fas fa-book"></i>Bookers</strong> !!
          </h1>
          <p>in <strong><i class="fas fa-book"></i>Bookers</strong> ,</p>
          <p>you can share and exchange your opinions , inpressions , and emotions</p>
          <p> about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  
  <footer></footer>
  
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">

  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <header>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <nav class="navbar navbar-expand-lg navbar-darkbg-dark">
        <div class="container">
          <a class="navbar-brand" href="https://837ac31add5d4b5bb97825537b1ce173.vfs.cloud9.ap-northeast-1.amazonaws.com/">
          <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" date-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown"></div>

      <% if user_signed_in? %>
      <li>
        <i class="fas fa-home"></i><%= link_to 'Home', user_path(current_user.id) %>
      </li>

      <li>
        <i class="fas fa-users"></i><%= link_to 'Users', users_path %>
      </li>

      <li>
        <i class="fas fa-book-open"></i><%= link_to 'Books', books_path %>
      </li>

      <li>
       <i class="fas fa-sign-out-alt"></i><%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
      <% else %>
      <li>
        <i class="fas fa-home"></i><%= link_to 'Home', root_path %>
      </li>

      <li>
        <i class="fas fa-link"></i><%= link_to 'About', about_path %>
      </li>

      <li>
        <i class="fas fa-user-plus"></i><%= link_to "Sign up", new_user_registration_path %>
      </li>

      <li>
        <i class="fas fa-sign-in-alt"></i><%= link_to "Log in", new_user_session_path %>
      </li>
      <% end %>

      </div>
      </nav>
    </header>



    <%= yield %>



     <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="input Image">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputintroduction" %>
  <%= f.submit "Update User" %>
  
<% end %>

app/views/users/index.html.erb
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
<!--userが沢山いるエリア-->
  <body>
    <div>
  <%= flash[:notice] %>
    </div>

      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <!--多分ヘッダーのなにかをのせるんだとおもう-->
        </nav>
      </header>

      <main>
        <p id="notice"></p>
        
        <div class="container px-5 px-sm-0">
          <div class="row">
            <!--ここからテンプレート-->
            <div class="col-md-3">
              <h2>User info</h2>
               <%= image_tag @user.get_profile_image(100,100) %>
               <table class="table">
                 <tbody>
                   <div>name【<%= @user.name %>】</div>

                   <div>introduction【<%= @user.introduction %>】</div>
                 </tbody>
               </table>

        <div class="row">
          <% if @user == current_user %>
            <i class="fas fa-wrench"></i><%= link_to "edit", edit_user_path(@user) %><i class="fas fa-user-cog"></i></i> <!--後で画像でリンクつなげる-->
          <% end %>
        </div>


       <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>

           <p>Title</p>
          <%= f.text_field :title %>
          <p>Opinion</p>
          <%= f.text_area :body %>
           <%= f.submit 'Create Book' %>
        <% end %>

            </div>
          <div class="col-md-8 offset-md-1">
          <h2>Users</h2>
          　<table class="table">
          　 <thead>
            　 <tr>
            　    <th>image</th>
              　   <th>name</th>
              　   <th colspan="3"></th>
            　 </tr>
          　 </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <th><%= image_tag user.get_profile_image(100,100) %></th>
              <th><%= user.name %></th>
              <th colspan="1">
                <%= link_to user_path(user.id) do %>
                  Show
                <% end %>
            <% end %>
              </th>
            </tr>
          </tbody>
        </table>
        </div>
       </div>
      </main>
      <footer></footer>
  </body>
</html>

app/views/users/new.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<h1>New Book</h1>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    
    <h4>Opinion</h4>
      <%= f.text_area :body %>
      
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/users/show.html.erb
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
<!--マイページに該当する部分(エディット直でいける)-->
  <body>
    <div>
  <%= flash[:notice] %>
    </div>

      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <!--多分ヘッダーのなにかをのせるんだとおもう-->
        </nav>
      </header>

      <main>
        <p id="notice"></p>

        <div class="container px-5 px-sm-0">
          <div class="row">
            <!--ここからテンプレート-->
            <div class="col-md-3">
              <h2>User info</h2>
               <%= image_tag @user.get_profile_image(100,100) %>
               <table class="table">
                 <tbody>
                   <div>name【<%= @user.name %>】</div>

                   <div>introduction【<%= @user.introduction %>】</div>
                 </tbody>
               </table>

        <div class="row">
          
            <i class="fas fa-wrench"></i><%= link_to "edit", edit_user_path(@user) %><i class="fas fa-user-cog"></i> <!--後で画像でリンクつなげる-->
         
        </div>


       <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>
        <form action="/books" accept-charset="UTF-8" method="post">
           <p>Title</p>
          <%= f.text_field :title %>
          <p>Opinion</p>
          <%= f.text_area :body %>
           <%= f.submit 'Create Book' %>
        <% end %>
        </form>
            </div>

        <!--ここまでテンプレート-->
         <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          　<table class="table table-hover table-inverse">
          　 <thead>
            　 <tr>
            　    <th></th>
              　   <th>Title</th>
              　   <th>Opinion</th>
              　   <th colspan="3"></th>
            　 </tr>
          　 </thead>

            <% @books.each do |book| %>
            <thead>
            <tr>
              <th>
                  <%= link_to user_path do %>
                  <%= image_tag book.user.get_profile_image(100,100) %></th>
                  <% end %>
              <th>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
              </th>
              <th><%= book.body %></th>
              <th colspan="3"><!--３つのリンク--></th>
            </tr>
            </thead>
          <% end %>




          </table>
        </div>
       </div>
      </main>
  </body>
</html>